%S%B%? WAITS=WATSIT(XLR)+HEAD+OUTER+NETDEF+JOBDAT+CACDAT+UNCDAT+P2COMM;
+LOWCOR+PARSER+SYSINI;
+MPXSER+KLSER+COMCSS+CLKSER+PAGSER;
+UUOCON+SPWSER+SCHEDU+SWPSER+CORE;
+DPYSER+TTYSER+VDPSER+LINED+DLNSER;
+DSKSER+DTCSER+MTCSER+TVSER+LPTSER+ELFSER+CARSER;
+XGPSER+PTPSER+PTRSER+IMPSER+PUPSER+DOMSER+NULSER;
+TAIL+ONCEND,; used to be TAIL+DDT+ONCE
;
;The order is important.  Make universal files if needed:
MACSYM/NOLOAD, MONSYM/NOLOAD, PHYPAR/NOLOAD, PROLOG/NOLOAD=PROLOG+BUGS+GLOBS,
PHYDAT.MAC,PHYSIO.MAC,PHYP4.MAC,PHYH2.MAC,PHYM78.MAC,
;
;Order of the following files is important
F/NOLOAD,S/NOLOAD,;universals.
NETMAC=NETMAC+IMPDDB,;has some globals.
NETSUB.MAC,IMPINT.MAC,IPSER.MAC,UDPSER.MAC,TCPSER.MAC,IMPMAC.MAC,;
;
;Separate assembly for DDT and ONCE:
P1END=WATSIT(XLR)+P1END+HEAD+OUTER+CHKEND+DDT+ONCE+ONCEND
